# FileMaker Sync Configuration
# Updated: 2025-06-16T14:54:06.301633

[database.source]
dsn = "rat"
user = "train"
pwd = ""
host = "127.0.0.1"
port = ""
type = "odbc"
name = ["fmp", "FileMaker Pro"]
schema = ["FileMaker_Tables", "FileMaker_Fields", "FileMaker_BaseTableFields"]

[database.target]
dsn = "postgres"
db = "supabase"
dt = "%Y%m%d %H:%M:%S"
type = "url"
host = "aws-0-eu-central-1.pooler.supabase.com"
schema = ["rat_migration", "rat"]
mig_schema = 0
tgt_schema = 1
user = "migration_user"

[database.target.supabase]
name = ["supabase", "Supabase"]
user = "postgres.kmoehqdowgdupzdxtbei"
pwd = "N1ceBigdatabase!"
port = "5432"

[export]
path = "/dev/RAT_Trains_Project/Migration/exports"
prefix = "rat"
image_formats_supported = ['jpg', 'webp']
image_path = "images"

[debug]
log_level = "DEBUG"
console_logging = true
max_log_entries = 1000
debug_mode = true
verbose_sql = true
debug_connections = true
